import "./globals.css";
import BootstrapClient from "@/common/BootstrapClient";
import "bootstrap/dist/css/bootstrap.min.css";
import Header from "@/containers/Header";
import Footer from "@/containers/Footer";

export const metadata = {
  title: "First Floor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer />
        <BootstrapClient />
      </body>
    </html>
  );
}
